version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7 
    container_name: url_shortener_mysql
    command: mysqld --user=root
    volumes:
      - ./urls.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=tgtools
      - MYSQL_ROOT_PASSWORD=golang
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
